//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace sde_pushMQ.WCFsde {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetActivatedScheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecuteSchedulerOperationCompleted;
        
        private System.Threading.SendOrPostCallback PushNetsuiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback PullNetsuiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback PushMQOperationCompleted;
        
        private System.Threading.SendOrPostCallback PullMQOperationCompleted;
        
        private System.Threading.SendOrPostCallback DoWorkOperationCompleted;
        
        private System.Threading.SendOrPostCallback WelComeMessageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::sde_pushMQ.Properties.Settings.Default.sde_pushMQ_WCFsde_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetActivatedScheduleCompletedEventHandler GetActivatedScheduleCompleted;
        
        /// <remarks/>
        public event ExecuteSchedulerCompletedEventHandler ExecuteSchedulerCompleted;
        
        /// <remarks/>
        public event PushNetsuiteCompletedEventHandler PushNetsuiteCompleted;
        
        /// <remarks/>
        public event PullNetsuiteCompletedEventHandler PullNetsuiteCompleted;
        
        /// <remarks/>
        public event PushMQCompletedEventHandler PushMQCompleted;
        
        /// <remarks/>
        public event PullMQCompletedEventHandler PullMQCompleted;
        
        /// <remarks/>
        public event DoWorkCompletedEventHandler DoWorkCompleted;
        
        /// <remarks/>
        public event WelComeMessageCompletedEventHandler WelComeMessageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetActivatedSchedule", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/sde.WCF")]
        public SchedulerEntity[] GetActivatedSchedule() {
            object[] results = this.Invoke("GetActivatedSchedule", new object[0]);
            return ((SchedulerEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetActivatedScheduleAsync() {
            this.GetActivatedScheduleAsync(null);
        }
        
        /// <remarks/>
        public void GetActivatedScheduleAsync(object userState) {
            if ((this.GetActivatedScheduleOperationCompleted == null)) {
                this.GetActivatedScheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActivatedScheduleOperationCompleted);
            }
            this.InvokeAsync("GetActivatedSchedule", new object[0], this.GetActivatedScheduleOperationCompleted, userState);
        }
        
        private void OnGetActivatedScheduleOperationCompleted(object arg) {
            if ((this.GetActivatedScheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActivatedScheduleCompleted(this, new GetActivatedScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExecuteScheduler", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExecuteScheduler() {
            object[] results = this.Invoke("ExecuteScheduler", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteSchedulerAsync() {
            this.ExecuteSchedulerAsync(null);
        }
        
        /// <remarks/>
        public void ExecuteSchedulerAsync(object userState) {
            if ((this.ExecuteSchedulerOperationCompleted == null)) {
                this.ExecuteSchedulerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteSchedulerOperationCompleted);
            }
            this.InvokeAsync("ExecuteScheduler", new object[0], this.ExecuteSchedulerOperationCompleted, userState);
        }
        
        private void OnExecuteSchedulerOperationCompleted(object arg) {
            if ((this.ExecuteSchedulerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteSchedulerCompleted(this, new ExecuteSchedulerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/PushNetsuite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PushNetsuite() {
            object[] results = this.Invoke("PushNetsuite", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PushNetsuiteAsync() {
            this.PushNetsuiteAsync(null);
        }
        
        /// <remarks/>
        public void PushNetsuiteAsync(object userState) {
            if ((this.PushNetsuiteOperationCompleted == null)) {
                this.PushNetsuiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushNetsuiteOperationCompleted);
            }
            this.InvokeAsync("PushNetsuite", new object[0], this.PushNetsuiteOperationCompleted, userState);
        }
        
        private void OnPushNetsuiteOperationCompleted(object arg) {
            if ((this.PushNetsuiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushNetsuiteCompleted(this, new PushNetsuiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/PullNetsuite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PullNetsuite() {
            object[] results = this.Invoke("PullNetsuite", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PullNetsuiteAsync() {
            this.PullNetsuiteAsync(null);
        }
        
        /// <remarks/>
        public void PullNetsuiteAsync(object userState) {
            if ((this.PullNetsuiteOperationCompleted == null)) {
                this.PullNetsuiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPullNetsuiteOperationCompleted);
            }
            this.InvokeAsync("PullNetsuite", new object[0], this.PullNetsuiteOperationCompleted, userState);
        }
        
        private void OnPullNetsuiteOperationCompleted(object arg) {
            if ((this.PullNetsuiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PullNetsuiteCompleted(this, new PullNetsuiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/PushMQ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PushMQ() {
            object[] results = this.Invoke("PushMQ", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PushMQAsync() {
            this.PushMQAsync(null);
        }
        
        /// <remarks/>
        public void PushMQAsync(object userState) {
            if ((this.PushMQOperationCompleted == null)) {
                this.PushMQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushMQOperationCompleted);
            }
            this.InvokeAsync("PushMQ", new object[0], this.PushMQOperationCompleted, userState);
        }
        
        private void OnPushMQOperationCompleted(object arg) {
            if ((this.PushMQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushMQCompleted(this, new PushMQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/PullMQ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PullMQ() {
            object[] results = this.Invoke("PullMQ", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PullMQAsync() {
            this.PullMQAsync(null);
        }
        
        /// <remarks/>
        public void PullMQAsync(object userState) {
            if ((this.PullMQOperationCompleted == null)) {
                this.PullMQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPullMQOperationCompleted);
            }
            this.InvokeAsync("PullMQ", new object[0], this.PullMQOperationCompleted, userState);
        }
        
        private void OnPullMQOperationCompleted(object arg) {
            if ((this.PullMQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PullMQCompleted(this, new PullMQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DoWork", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DoWork() {
            this.Invoke("DoWork", new object[0]);
        }
        
        /// <remarks/>
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        /// <remarks/>
        public void DoWorkAsync(object userState) {
            if ((this.DoWorkOperationCompleted == null)) {
                this.DoWorkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoWorkOperationCompleted);
            }
            this.InvokeAsync("DoWork", new object[0], this.DoWorkOperationCompleted, userState);
        }
        
        private void OnDoWorkOperationCompleted(object arg) {
            if ((this.DoWorkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/WelComeMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WelComeMessage([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            object[] results = this.Invoke("WelComeMessage", new object[] {
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WelComeMessageAsync(string name) {
            this.WelComeMessageAsync(name, null);
        }
        
        /// <remarks/>
        public void WelComeMessageAsync(string name, object userState) {
            if ((this.WelComeMessageOperationCompleted == null)) {
                this.WelComeMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWelComeMessageOperationCompleted);
            }
            this.InvokeAsync("WelComeMessage", new object[] {
                        name}, this.WelComeMessageOperationCompleted, userState);
        }
        
        private void OnWelComeMessageOperationCompleted(object arg) {
            if ((this.WelComeMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WelComeMessageCompleted(this, new WelComeMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/sde.WCF")]
    public partial class SchedulerEntity {
        
        private System.Nullable<System.DateTime> sche_dateField;
        
        private bool sche_dateFieldSpecified;
        
        private System.Nullable<System.DateTime> sche_lastRunField;
        
        private bool sche_lastRunFieldSpecified;
        
        private System.Nullable<int> sche_lastRunSeqNoField;
        
        private bool sche_lastRunSeqNoFieldSpecified;
        
        private string sche_minuteGapField;
        
        private System.Nullable<System.DateTime> sche_nextRunField;
        
        private bool sche_nextRunFieldSpecified;
        
        private System.Nullable<int> sche_nextRunSeqNoField;
        
        private bool sche_nextRunSeqNoFieldSpecified;
        
        private string sche_statusField;
        
        private string sche_transactionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> sche_date {
            get {
                return this.sche_dateField;
            }
            set {
                this.sche_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sche_dateSpecified {
            get {
                return this.sche_dateFieldSpecified;
            }
            set {
                this.sche_dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> sche_lastRun {
            get {
                return this.sche_lastRunField;
            }
            set {
                this.sche_lastRunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sche_lastRunSpecified {
            get {
                return this.sche_lastRunFieldSpecified;
            }
            set {
                this.sche_lastRunFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> sche_lastRunSeqNo {
            get {
                return this.sche_lastRunSeqNoField;
            }
            set {
                this.sche_lastRunSeqNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sche_lastRunSeqNoSpecified {
            get {
                return this.sche_lastRunSeqNoFieldSpecified;
            }
            set {
                this.sche_lastRunSeqNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sche_minuteGap {
            get {
                return this.sche_minuteGapField;
            }
            set {
                this.sche_minuteGapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> sche_nextRun {
            get {
                return this.sche_nextRunField;
            }
            set {
                this.sche_nextRunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sche_nextRunSpecified {
            get {
                return this.sche_nextRunFieldSpecified;
            }
            set {
                this.sche_nextRunFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> sche_nextRunSeqNo {
            get {
                return this.sche_nextRunSeqNoField;
            }
            set {
                this.sche_nextRunSeqNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sche_nextRunSeqNoSpecified {
            get {
                return this.sche_nextRunSeqNoFieldSpecified;
            }
            set {
                this.sche_nextRunSeqNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sche_status {
            get {
                return this.sche_statusField;
            }
            set {
                this.sche_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sche_transactionType {
            get {
                return this.sche_transactionTypeField;
            }
            set {
                this.sche_transactionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetActivatedScheduleCompletedEventHandler(object sender, GetActivatedScheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActivatedScheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActivatedScheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchedulerEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchedulerEntity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ExecuteSchedulerCompletedEventHandler(object sender, ExecuteSchedulerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteSchedulerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteSchedulerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PushNetsuiteCompletedEventHandler(object sender, PushNetsuiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushNetsuiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushNetsuiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PullNetsuiteCompletedEventHandler(object sender, PullNetsuiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PullNetsuiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PullNetsuiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PushMQCompletedEventHandler(object sender, PushMQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushMQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushMQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PullMQCompletedEventHandler(object sender, PullMQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PullMQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PullMQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DoWorkCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WelComeMessageCompletedEventHandler(object sender, WelComeMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WelComeMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WelComeMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591