//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class backorder_cancellation
    {
        public int boc_recid { get; set; }
        public string boc_isbn { get; set; }
        public string boc_moNo { get; set; }
        public string boc_quantity { get; set; }
        public Nullable<System.DateTime> boc_createdDate { get; set; }
        public string boc_sourceFile { get; set; }
        public Nullable<int> boc_insertSequence { get; set; }
        public string boc_netsuiteProcess { get; set; }
        public string boc_netsuiteJob { get; set; }
        public string boc_netsuiteJobStatus { get; set; }
        public string boc_netsuiteJobError { get; set; }
    }
}
