//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcas_salestransaction
    {
        public int bst_recID { get; set; }
        public Nullable<System.DateTime> bst_createdDate { get; set; }
        public string bst_soInternalID { get; set; }
        public string bst_ifSeqNo { get; set; }
        public string bst_ifJobID { get; set; }
        public string bst_ifInternalID { get; set; }
        public Nullable<System.DateTime> bst_ifUpdatedDate { get; set; }
        public string bst_invSeqNo { get; set; }
        public string bst_invJobID { get; set; }
        public string bst_invInternalID { get; set; }
        public Nullable<System.DateTime> bst_invUpdatedDate { get; set; }
        public string bst_invProgressStatus { get; set; }
        public Nullable<System.DateTime> bst_postingDate { get; set; }
    }
}
