//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcas_journalcalclist
    {
        public int jcl_recID { get; set; }
        public Nullable<float> jcl_amt { get; set; }
        public string jcl_job_ID { get; set; }
        public string jcl_businessChannel_code { get; set; }
        public string jcl_country_tag { get; set; }
        public string jcl_country_internalID { get; set; }
        public string jcl_currency_internalID { get; set; }
        public Nullable<System.DateTime> jcl_jos_rangeTo { get; set; }
        public string jcl_moNo { get; set; }
        public Nullable<System.DateTime> jcl_createdDate { get; set; }
        public Nullable<System.DateTime> jcl_rangeFrom { get; set; }
        public Nullable<System.DateTime> jcl_rangeTo { get; set; }
    }
}
