//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcas_otherstransaction
    {
        public int bot_recID { get; set; }
        public string bot_subsidiary { get; set; }
        public string bot_subsidiaryInternalID { get; set; }
        public string bot_refNo { get; set; }
        public string bot_invInternalID { get; set; }
        public Nullable<System.DateTime> bot_invDate { get; set; }
        public string bot_salesType { get; set; }
        public string bot_trxType { get; set; }
        public string bot_seqNo { get; set; }
        public string bot_trxInternalID { get; set; }
        public Nullable<System.DateTime> bot_trxUpdatedDate { get; set; }
        public string bot_trxProgressStatus { get; set; }
        public string bot_irInternalID { get; set; }
        public Nullable<System.DateTime> bot_irUpdateDate { get; set; }
        public string bot_irProgressStatus { get; set; }
        public string bot_irSeqNo { get; set; }
        public string bot_cnInternalID { get; set; }
        public Nullable<System.DateTime> bot_cnUpdatedDate { get; set; }
        public string bot_cnProgressStatus { get; set; }
        public string bot_cnSeqNo { get; set; }
        public string bot_crInternalID { get; set; }
        public Nullable<System.DateTime> bot_crUpdatedDate { get; set; }
        public string bot_crProgressStatus { get; set; }
        public string bot_crSeqNo { get; set; }
        public Nullable<System.DateTime> bot_postingDate { get; set; }
    }
}
