//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcas_sep_sales
    {
        public string country { get; set; }
        public string mo_type { get; set; }
        public string isbn { get; set; }
        public Nullable<int> quantity { get; set; }
        public string sales_type { get; set; }
    }
}
