//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcas_sep_loaded
    {
        public string type { get; set; }
        public string item_isbn { get; set; }
        public Nullable<int> my_qty { get; set; }
        public Nullable<int> sg_qty { get; set; }
        public Nullable<int> id_qty { get; set; }
    }
}
