//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Book_ID { get; set; }
        public string Book_Name { get; set; }
        public string Book_Genre { get; set; }
        public string Book_Author { get; set; }
        public string Book_Pages { get; set; }
        public string Book_PublishYear { get; set; }
        public string Book_Edition { get; set; }
    }
}
