//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpas_otherstransaction
    {
        public int cot_recID { get; set; }
        public string cot_subsidiary { get; set; }
        public string cot_subsidiaryInternalID { get; set; }
        public string cot_refNo { get; set; }
        public string cot_invInternalID { get; set; }
        public Nullable<System.DateTime> cot_invDate { get; set; }
        public string cot_salesType { get; set; }
        public string cot_trxType { get; set; }
        public string cot_seqNo { get; set; }
        public string cot_trxInternalID { get; set; }
        public Nullable<System.DateTime> cot_trxUpdatedDate { get; set; }
        public string cot_trxProgressStatus { get; set; }
        public string cot_irInternalID { get; set; }
        public Nullable<System.DateTime> cot_irUpdateDate { get; set; }
        public string cot_irProgressStatus { get; set; }
        public string cot_irSeqNo { get; set; }
        public string cot_cnInternalID { get; set; }
        public Nullable<System.DateTime> cot_cnUpdatedDate { get; set; }
        public string cot_cnProgressStatus { get; set; }
        public string cot_cnSeqNo { get; set; }
        public string cot_crInternalID { get; set; }
        public Nullable<System.DateTime> cot_crUpdatedDate { get; set; }
        public string cot_crProgressStatus { get; set; }
        public string cot_crSeqNo { get; set; }
        public Nullable<System.DateTime> cot_postingDate { get; set; }
        public string cot_ml_location_internalID { get; set; }
        public string cot_sp_id { get; set; }
        public string cot_cnGIFIInternalID { get; set; }
        public Nullable<System.DateTime> cot_cnGIFIUpdatedDate { get; set; }
        public string cot_cnGIFIProgressStatus { get; set; }
        public string cot_cnGIFISeqNo { get; set; }
        public string cot_vcInternalID { get; set; }
        public Nullable<System.DateTime> cot_vcUpdatedDate { get; set; }
        public string cot_vcProgressStatus { get; set; }
        public string cot_vcSeqNo { get; set; }
        public string cot_vcGIFIInternalID { get; set; }
        public Nullable<System.DateTime> cot_vcGIFIUpdatedDate { get; set; }
        public string cot_vcGIFIProgressStatus { get; set; }
        public string cot_vcGIFISeqNo { get; set; }
        public string cot_suspendDate { get; set; }
    }
}
