//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpas_salestransaction_history
    {
        public int cst_recID { get; set; }
        public string cst_refNo { get; set; }
        public Nullable<System.DateTime> cst_createdDate { get; set; }
        public string cst_soSeqNo { get; set; }
        public string cst_soJobID { get; set; }
        public string cst_soInternalID { get; set; }
        public Nullable<System.DateTime> cst_soUpdatedDate { get; set; }
        public string cst_ifSeqNo { get; set; }
        public string cst_ifJobID { get; set; }
        public string cst_ifInternalID { get; set; }
        public Nullable<System.DateTime> cst_ifUpdatedDate { get; set; }
        public string cst_invSeqNo { get; set; }
        public string cst_invJobID { get; set; }
        public string cst_invInternalID { get; set; }
        public Nullable<System.DateTime> cst_invUpdatedDate { get; set; }
        public string cst_invProgressStatus { get; set; }
        public string cst_sp_id { get; set; }
        public string cst_sDesc { get; set; }
        public string cst_sLoc { get; set; }
        public string cst_ml_location_internalID { get; set; }
        public string cst_subsidiary { get; set; }
        public string cst_subsidiary_internalID { get; set; }
        public Nullable<System.DateTime> cst_postingDate { get; set; }
        public string cst_salesType { get; set; }
    }
}
