//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpas_presales
    {
        public int ps_id { get; set; }
        public string ps_tranType { get; set; }
        public string ps_subsidiary { get; set; }
        public string ps_subsidiary_internalID { get; set; }
        public string ps_businessChannel { get; set; }
        public string ps_businessChannel_internalID { get; set; }
        public Nullable<double> ps_amount { get; set; }
        public Nullable<int> ps_month { get; set; }
        public Nullable<int> ps_year { get; set; }
        public Nullable<System.DateTime> ps_tranDate { get; set; }
        public Nullable<System.DateTime> ps_createdDate { get; set; }
        public string ps_jn_journalID { get; set; }
    }
}
