//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpas_journal
    {
        public int jn_recID { get; set; }
        public string jn_account { get; set; }
        public string jn_account_internalID { get; set; }
        public string jn_tranType { get; set; }
        public string jn_subsidiary { get; set; }
        public string jn_subsidiary_internalID { get; set; }
        public string jn_businessChannel { get; set; }
        public string jn_businessChannel_internalID { get; set; }
        public string jn_desc { get; set; }
        public Nullable<double> jn_drAmount { get; set; }
        public Nullable<double> jn_crAmount { get; set; }
        public Nullable<System.DateTime> jn_postingDate { get; set; }
        public Nullable<int> jn_postingWeek { get; set; }
        public Nullable<int> jn_postingMonth { get; set; }
        public Nullable<int> jn_postingYear { get; set; }
        public Nullable<System.DateTime> jn_createdDate { get; set; }
        public Nullable<System.DateTime> jn_rangeTo { get; set; }
        public Nullable<bool> jn_isMonthlyUnship { get; set; }
        public string jn_journalID { get; set; }
    }
}
