//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dashboard_salesorder
    {
        public string nsj_jobID { get; set; }
        public string nsjm_jobMo_ID { get; set; }
        public string nsj_businessChannel_ID { get; set; }
        public string nsj_country_tag { get; set; }
        public Nullable<int> nsj_job_mo_count { get; set; }
        public string nsjm_moNo { get; set; }
        public string nsjm_moNo_internalID { get; set; }
        public Nullable<System.DateTime> nsj_rangeTo { get; set; }
    }
}
