//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class default_forwarder
    {
        public string countryCode { get; set; }
        public string code { get; set; }
        public string postcode { get; set; }
        public string telNo { get; set; }
        public string faxNo { get; set; }
        public string cNote { get; set; }
        public string countryName { get; set; }
        public string state { get; set; }
        public string email { get; set; }
        public string homepage { get; set; }
        public string coName { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string city { get; set; }
        public string coLisence { get; set; }
        public string fobPostCode { get; set; }
        public string fobTelNo { get; set; }
        public string fobFaxNo { get; set; }
        public string fobState { get; set; }
        public string fobCountry { get; set; }
        public string uen { get; set; }
        public string contact_name { get; set; }
        public string focCoName { get; set; }
        public string fobAddr1 { get; set; }
        public string fobAddr2 { get; set; }
        public string fobCity { get; set; }
        public string fobContactName { get; set; }
        public string fobUen { get; set; }
        public Nullable<decimal> gst { get; set; }
        public Nullable<decimal> countryRate { get; set; }
    }
}
