//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dummyso
    {
        public int dso_recID { get; set; }
        public string dso_soInternalId { get; set; }
        public string dso_itemInternalId { get; set; }
        public string dso_oriQuantity { get; set; }
        public string dso_newQuantity { get; set; }
        public string dso_amount { get; set; }
        public Nullable<System.DateTime> dso_createdDate { get; set; }
        public Nullable<System.DateTime> dso_rangeTo { get; set; }
        public string dso_subsidiary { get; set; }
        public string dso_businessChannel { get; set; }
    }
}
