//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorlog_cpas_stockposting
    {
        public int recID { get; set; }
        public string so_sPID { get; set; }
        public string so_sProduct { get; set; }
        public string so_sDesc { get; set; }
        public string so_sCon { get; set; }
        public string so_sBatch { get; set; }
        public Nullable<decimal> so_dQty { get; set; }
        public Nullable<decimal> so_dQty3 { get; set; }
        public string so_sLoc { get; set; }
        public string so_sDesc2 { get; set; }
        public string so_name { get; set; }
        public string so_businessChannel { get; set; }
        public string so_country { get; set; }
        public string so_transactionType { get; set; }
        public Nullable<System.DateTime> so_transactionDate { get; set; }
        public Nullable<System.DateTime> so_syncDate { get; set; }
        public string so_postingPeriod { get; set; }
        public Nullable<bool> so_postInd { get; set; }
        public Nullable<System.DateTime> so_createdDate { get; set; }
        public Nullable<System.DateTime> so_readyPushDate { get; set; }
    }
}
