//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class excesspo
    {
        public int ep_recID { get; set; }
        public string ep_prID { get; set; }
        public string ep_poreceiveID { get; set; }
        public string ep_poreceiveItemID { get; set; }
        public string ep_itemInternalID { get; set; }
        public Nullable<int> ep_excessQty { get; set; }
        public Nullable<System.DateTime> ep_createdDate { get; set; }
        public Nullable<System.DateTime> ep_rangeTo { get; set; }
    }
}
