//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_tem
    {
        public string item_id { get; set; }
        public string name { get; set; }
        public string internal_id { get; set; }
        public string location { get; set; }
        public Nullable<int> locationavailable { get; set; }
        public Nullable<double> weight { get; set; }
        public string product_category { get; set; }
        public string legacy_code { get; set; }
        public string isbn { get; set; }
    }
}
