//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_businesschannel
    {
        public string mb_businessChannel_internalID { get; set; }
        public string mb_businessChannel_name { get; set; }
        public string mb_businessChannel_parent { get; set; }
        public Nullable<bool> mb_businessChannel_includeChild { get; set; }
        public Nullable<bool> mb_businessChannel_isInActive { get; set; }
        public string mb_imas_businessChannel_ID { get; set; }
        public string mb_imas_businessChannel_code { get; set; }
    }
}
