//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_chartofaccount
    {
        public int coa_recID { get; set; }
        public string coa_tranType { get; set; }
        public string coa_accountNo { get; set; }
        public string coa_account_internalID { get; set; }
        public string coa_glType { get; set; }
        public string coa_subsidiary { get; set; }
    }
}
