//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_country
    {
        public int mc_recID { get; set; }
        public string mc_countryCode { get; set; }
        public string mc_countryName { get; set; }
        public string mc_country_internalID { get; set; }
    }
}
