//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_itemprice
    {
        public int mip_recID { get; set; }
        public string mip_item_isbn { get; set; }
        public string mip_item_pricelevel { get; set; }
        public Nullable<double> mip_item_price { get; set; }
        public string mip_item_currency { get; set; }
        public string mip_item_internalID { get; set; }
    }
}
