//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_location
    {
        public string ml_location_internalID { get; set; }
        public string ml_location_name { get; set; }
        public string ml_location_parent { get; set; }
        public string ml_location_country { get; set; }
        public Nullable<bool> ml_location_isInactive { get; set; }
    }
}
