//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_currency
    {
        public int mc_currency_recID { get; set; }
        public string mc_currency_internalID { get; set; }
        public string mc_currency_name { get; set; }
        public string mc_currency_ISO_code { get; set; }
        public string mc_country { get; set; }
    }
}
