//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_bin
    {
        public string mb_bin_internalID { get; set; }
        public string mb_bin_name { get; set; }
        public string mb_bin_location_internalID { get; set; }
        public string mb_bin_branch_internalID { get; set; }
        public string mb_returnbin_name { get; set; }
        public string mb_returnbin_location_internalID { get; set; }
        public Nullable<bool> mb_bin_isInactive { get; set; }
    }
}
