//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_subsidiary
    {
        public string ms_subsidiary_internalID { get; set; }
        public string ms_subsidiary_name { get; set; }
        public string ms_subsidiary_parent { get; set; }
        public string ms_subsidiary_country { get; set; }
        public Nullable<bool> ms_subsidiary_isInactive { get; set; }
        public string ms_countryName { get; set; }
        public string ms_currency { get; set; }
        public string ms_currencyCode { get; set; }
    }
}
