//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_job
    {
        public string nsj_jobID { get; set; }
        public string nsj_businessChannel_ID { get; set; }
        public string nsj_country_tag { get; set; }
        public string nsj_mc_countryCode { get; set; }
        public string nsj_createdBy { get; set; }
        public bool nsj_job_active { get; set; }
        public string nsj_job_description { get; set; }
        public Nullable<int> nsj_job_mo_count { get; set; }
        public string nsj_job_no { get; set; }
        public Nullable<short> nsj_job_status { get; set; }
        public string nsj_modifiedBy { get; set; }
        public Nullable<System.DateTime> nsj_modifiedDate { get; set; }
        public Nullable<System.DateTime> nsj_createdDate { get; set; }
        public Nullable<System.DateTime> nsj_rangeTo { get; set; }
        public int nsj_recID { get; set; }
    }
}
