//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_setting
    {
        public string nss_account { get; set; }
        public string nss_password { get; set; }
        public Nullable<System.DateTime> nss_expired { get; set; }
        public string sandbox_password { get; set; }
    }
}
