//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_newso_history
    {
        public int nt1_seqID { get; set; }
        public string nt1_moNo { get; set; }
        public string nt1_moNo_internalID { get; set; }
        public string nt1_status { get; set; }
        public string nt1_itemID { get; set; }
        public string nt1_item_internalID { get; set; }
        public Nullable<int> nt1_ordQty { get; set; }
        public Nullable<int> nt1_committedQty { get; set; }
        public Nullable<int> nt1_fulfilledQty { get; set; }
        public Nullable<double> nt1_tax { get; set; }
        public Nullable<double> nt1_discount { get; set; }
        public Nullable<double> nt1_rate { get; set; }
        public Nullable<double> nt1_amount { get; set; }
        public string nt1_customer { get; set; }
        public string nt1_customer_internalID { get; set; }
        public string nt1_SEIS_moNo { get; set; }
        public string nt1_SEIS_moNo_internalID { get; set; }
        public string nt1_subsidiary { get; set; }
        public Nullable<System.DateTime> nt1_createdDate { get; set; }
        public Nullable<System.DateTime> nt1_rangeTo { get; set; }
        public string nt1_synctowms { get; set; }
        public string nt1_custID { get; set; }
        public string nt1_addressee { get; set; }
        public string nt1_deliveryAdd { get; set; }
        public string nt1_deliveryAdd2 { get; set; }
        public string nt1_deliveryAdd3 { get; set; }
        public string nt1_postCode { get; set; }
        public string nt1_contactPerson { get; set; }
        public string nt1_phone { get; set; }
        public string nt1_country { get; set; }
        public string nt1_billingAddressee { get; set; }
        public string nt1_billingAdd { get; set; }
        public string nt1_billingAdd2 { get; set; }
        public string nt1_billingAdd3 { get; set; }
        public string nt1_billingPostcode { get; set; }
        public string nt1_billingContactPerson { get; set; }
        public string nt1_billingPhone { get; set; }
        public string nt1_shipMethod { get; set; }
        public string nt1_creditTerm { get; set; }
        public Nullable<double> nt1_basedprice { get; set; }
        public string nt1_pricelevel { get; set; }
        public string nt1_memo { get; set; }
        public string nt1_ponumber { get; set; }
        public Nullable<int> nt1_itemLine { get; set; }
        public string nt1_discountItem_internalID { get; set; }
        public Nullable<System.DateTime> nt1_podate { get; set; }
        public string nt1_forwarderTo { get; set; }
        public string nt1_forwarderLabel { get; set; }
        public string nt1_forwarderAddressee { get; set; }
        public string nt1_forwarderAdd1 { get; set; }
        public string nt1_forwarderAdd2 { get; set; }
        public string nt1_forwarderAdd3 { get; set; }
        public string nt1_forwarderAttention { get; set; }
        public string nt1_forwarderState { get; set; }
        public string nt1_forwarderPostcode { get; set; }
        public string nt1_forwarderCity { get; set; }
        public string nt1_forwarderCountry { get; set; }
        public string nt1_forwarderPhone { get; set; }
        public string nt1_forwarderInternalID { get; set; }
    }
}
