//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_jobitem
    {
        public string nsji_jobItem_ID { get; set; }
        public string nsji_nsj_jobID { get; set; }
        public string nsji_createdBy { get; set; }
        public Nullable<System.DateTime> nsji_createdDate { get; set; }
        public string nsji_item_ID { get; set; }
        public string nsji_item_internalID { get; set; }
        public Nullable<decimal> nsji_item_qty { get; set; }
        public string nsji_posting_type { get; set; }
        public string nsji_moNo { get; set; }
        public string nsji_moNo_internalID { get; set; }
        public Nullable<System.DateTime> nsji_rangeTo { get; set; }
        public int nsji_recID { get; set; }
    }
}
