//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_transferdetail
    {
        public int natd_id { get; set; }
        public string natd_itemID { get; set; }
        public Nullable<int> natd_itemInternalID { get; set; }
        public Nullable<int> natd_qty { get; set; }
        public string natd_imasID { get; set; }
        public Nullable<int> natd_toLocID { get; set; }
        public Nullable<int> natd_fromLocID { get; set; }
        public Nullable<int> natd_subsidiaryID { get; set; }
        public Nullable<int> natd_businessChannelID { get; set; }
        public Nullable<System.DateTime> natd_date { get; set; }
        public Nullable<int> nat_postingPeriodID { get; set; }
    }
}
