//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_dropshipfulfillment
    {
        public int dsf_recID { get; set; }
        public string dsf_GMYmono { get; set; }
        public string dsf_GMYmono_internalID { get; set; }
        public string dsf_dropshipmono { get; set; }
        public string dsf_dropshipmono_internalID { get; set; }
        public string dsf_subsidiary { get; set; }
        public string dsf_status { get; set; }
        public string dsf_itemID { get; set; }
        public string dsf_item_internalID { get; set; }
        public string dsf_pricelevel { get; set; }
        public string dsf_pricelevel_InternalID { get; set; }
        public Nullable<double> dsf_rate { get; set; }
        public Nullable<int> dsf_ordQty { get; set; }
        public Nullable<int> dsf_wmsfulfilledqty { get; set; }
        public Nullable<int> dsf_createdinvoiceqty { get; set; }
        public Nullable<double> dsf_discount { get; set; }
        public string dsf_discountItem_internalID { get; set; }
        public string dsf_ponumber { get; set; }
        public string dsf_customer_InternalID { get; set; }
        public Nullable<System.DateTime> dsf_lastfulfilleddate { get; set; }
        public Nullable<System.DateTime> dsf_lastinvoicedate { get; set; }
        public Nullable<double> dsf_basedprice { get; set; }
        public string dsf_iffProgress { get; set; }
        public string dsf_iffSeqNo { get; set; }
        public Nullable<System.DateTime> dsf_iffUpdatedDate { get; set; }
        public string dsf_iffInternalID { get; set; }
        public string dsf_invProgress { get; set; }
        public string dsf_invSeqNo { get; set; }
        public Nullable<System.DateTime> dsf_invUpdatedDate { get; set; }
        public string dsf_invInternalID { get; set; }
        public string dsf_is_fas { get; set; }
        public string dsf_class_name { get; set; }
    }
}
