//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_pritem
    {
        public string nspi_pritem_ID { get; set; }
        public string nspi_item_ID { get; set; }
        public string nspi_itemBusiness_ID { get; set; }
        public string nspi_nspr_pr_ID { get; set; }
        public bool nspi_pritem_approved { get; set; }
        public string nspi_pritem_approvedBy { get; set; }
        public Nullable<System.DateTime> nspi_pritem_approvedDate { get; set; }
        public string nspi_pritem_comments { get; set; }
        public bool nspi_pritem_converted { get; set; }
        public int nspi_pritem_qty { get; set; }
        public Nullable<decimal> nspi_pritem_price { get; set; }
        public long nspi_sort { get; set; }
        public string nspi_item_internalID { get; set; }
        public Nullable<System.DateTime> nspi_createdDate { get; set; }
        public string nspi_pushStatus { get; set; }
        public string nspi_salesTerritorySCH { get; set; }
    }
}
