//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_transfer
    {
        public int nat_id { get; set; }
        public string nat_subsidiary { get; set; }
        public Nullable<int> nat_subsidiaryID { get; set; }
        public string nat_fromLoc { get; set; }
        public Nullable<int> nat_fromLocID { get; set; }
        public string nat_toLoc { get; set; }
        public Nullable<int> nat_toLocID { get; set; }
        public string nat_businessChannel { get; set; }
        public Nullable<int> nat_businessChannelID { get; set; }
        public string nat_Memo { get; set; }
        public Nullable<System.DateTime> nat_Date { get; set; }
        public string nat_postingPeriod { get; set; }
        public Nullable<int> nat_postingPeriodID { get; set; }
    }
}
