//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_invoice
    {
        public string nsinv_recID { get; set; }
        public string nsinv_moNo { get; set; }
        public string nsinv_moNo_internalID { get; set; }
        public string nsinv_entity { get; set; }
        public string nsinv_entity_internalID { get; set; }
        public Nullable<System.DateTime> nsinv_createdDate { get; set; }
        public Nullable<System.DateTime> nsinv_rangeTo { get; set; }
        public string nsinv_location { get; set; }
        public string nsinv_location_internalID { get; set; }
    }
}
