//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_adjustmentitem
    {
        public int nsdai_recID { get; set; }
        public string nsdai_adjustmentItem_ID { get; set; }
        public string nsdai_itemBusiness_ID { get; set; }
        public Nullable<decimal> nsdai_adjustmentItem_qty { get; set; }
        public string nsdai_nsda_adjustment_ID { get; set; }
        public Nullable<bool> nsdai_adjustmentItem_status { get; set; }
        public string nsdai_adjustmentItem_remarks { get; set; }
        public Nullable<System.DateTime> nsdai_createdDate { get; set; }
        public Nullable<System.DateTime> nsdai_rangeTo { get; set; }
    }
}
