//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_syncupdateso
    {
        public int nt3_seqID { get; set; }
        public string nt3_moNo { get; set; }
        public string nt3_moNo_internalID { get; set; }
        public string nt3_itemISBN { get; set; }
        public string nt3_item_internalID { get; set; }
        public Nullable<int> nt3_ordQty { get; set; }
        public Nullable<int> nt3_committedQty { get; set; }
        public Nullable<int> nt3_fulfilledQty { get; set; }
        public Nullable<double> nt3_tax { get; set; }
        public Nullable<double> nt3_discount { get; set; }
        public Nullable<double> nt3_rate { get; set; }
        public Nullable<double> nt3_amount { get; set; }
        public Nullable<double> nt3_basedPrice { get; set; }
        public Nullable<double> nt3_disctolvalue { get; set; }
        public Nullable<int> nt3_syncedfromNS { get; set; }
        public Nullable<int> nt3_syncedtoNS { get; set; }
        public Nullable<int> nt3_itemLine { get; set; }
        public Nullable<System.DateTime> nt3_createdDate { get; set; }
        public Nullable<System.DateTime> nt3_rangeTo { get; set; }
        public string nt3_progressStatus { get; set; }
    }
}
