//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_syncso
    {
        public int nt2_seqID { get; set; }
        public string nt2_moNo { get; set; }
        public string nt2_moNo_internalID { get; set; }
        public string nt2_status { get; set; }
        public string nt2_itemID { get; set; }
        public string nt2_item_internalID { get; set; }
        public Nullable<int> nt2_ordQty { get; set; }
        public Nullable<int> nt2_qtyForWMS { get; set; }
        public Nullable<int> nt2_fulfilledQty { get; set; }
        public Nullable<double> nt2_tax { get; set; }
        public Nullable<double> nt2_discount { get; set; }
        public Nullable<double> nt2_rate { get; set; }
        public Nullable<double> nt2_amount { get; set; }
        public string nt2_customer { get; set; }
        public string nt2_customer_internalID { get; set; }
        public string nt2_SEIS_moNo { get; set; }
        public string nt2_SEIS_moNo_internalID { get; set; }
        public string nt2_subsidiary { get; set; }
        public Nullable<System.DateTime> nt2_createdDate { get; set; }
        public Nullable<System.DateTime> nt2_rangeTo { get; set; }
        public string nt2_progressStatus { get; set; }
        public string nt2_custID { get; set; }
        public string nt2_addressee { get; set; }
        public string nt2_deliveryAdd { get; set; }
        public string nt2_deliveryAdd2 { get; set; }
        public string nt2_deliveryAdd3 { get; set; }
        public string nt2_postCode { get; set; }
        public string nt2_contactPerson { get; set; }
        public string nt2_phone { get; set; }
        public string nt2_country { get; set; }
        public string nt2_billingAddressee { get; set; }
        public string nt2_billingAdd { get; set; }
        public string nt2_billingAdd2 { get; set; }
        public string nt2_billingAdd3 { get; set; }
        public string nt2_billingPostcode { get; set; }
        public string nt2_billingContactPerson { get; set; }
        public string nt2_billingPhone { get; set; }
        public string nt2_shipMethod { get; set; }
        public string nt2_creditTerm { get; set; }
        public Nullable<double> nt2_basedprice { get; set; }
        public string nt2_pricelevel { get; set; }
        public Nullable<System.DateTime> nt2_lastModifiedDate { get; set; }
        public Nullable<int> nt2_wmsfulfilledqty { get; set; }
        public Nullable<System.DateTime> nt2_lastfulfilledDate { get; set; }
        public Nullable<int> nt2_unfulfilledQty { get; set; }
        public string nt2_businessChannel_internalID { get; set; }
        public string nt2_customer_booked { get; set; }
        public string nt2_is_fas { get; set; }
        public string nt2_teacher_name { get; set; }
        public string nt2_class_name { get; set; }
    }
}
