//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_jobmo_pack
    {
        public int nsjmp_recID { get; set; }
        public string nsjmp_jobmoPack_ID { get; set; }
        public string nsjmp_nsj_jobID { get; set; }
        public string nsjmp_period { get; set; }
        public string nsjmp_moNo { get; set; }
        public string nsjmp_schID { get; set; }
        public string nsjmp_schName { get; set; }
        public string nsjmp_packID { get; set; }
        public string nsjmp_packTitles { get; set; }
        public string nsjmp_item_internalID { get; set; }
        public Nullable<float> nsjmp_packPrice { get; set; }
        public Nullable<int> nsjmp_qty { get; set; }
        public Nullable<float> nsjmp_amt { get; set; }
        public string nsjmp_packISBN { get; set; }
        public string nsjmp_moNo_internalID { get; set; }
        public Nullable<System.DateTime> nsjmp_createdDate { get; set; }
        public Nullable<System.DateTime> nsjmp_rangeTo { get; set; }
    }
}
