//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_jobordmaster
    {
        public int nsjom_recID { get; set; }
        public string nsjom_jobOrdMaster_ID { get; set; }
        public string nsjom_nsj_job_ID { get; set; }
        public string nsjom_jobmo_id { get; set; }
        public string nsjom_ordRecNo { get; set; }
        public string nsjom_ordStudent { get; set; }
        public string nsjom_clsID { get; set; }
        public string nsjom_moNo { get; set; }
        public string nsjom_consignmentNote { get; set; }
        public Nullable<System.DateTime> nsjom_scanDate { get; set; }
        public string nsjom_processPeriod { get; set; }
        public string nsjom_country { get; set; }
        public string nsjom_moNo_internalID { get; set; }
        public Nullable<System.DateTime> nsjom_createdDate { get; set; }
        public Nullable<System.DateTime> nsjom_rangeTo { get; set; }
        public string nsjom_memo { get; set; }
        public string nsjom_jobCls_id { get; set; }
    }
}
