//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_returnrefund
    {
        public string nsrr_recID { get; set; }
        public string nsrr_number { get; set; }
        public string nsrr_internalID { get; set; }
        public Nullable<System.DateTime> nsrr_tranDate { get; set; }
        public Nullable<System.DateTime> nsrr_createdDate { get; set; }
        public Nullable<System.DateTime> nsrr_rangeTo { get; set; }
    }
}
