//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_syncso_tem
    {
        public int nt2_seqID { get; set; }
        public string nt2_moNo { get; set; }
        public string nt2_moNo_internalID { get; set; }
        public string nt2_status { get; set; }
        public string nt2_itemID { get; set; }
        public string nt2_item_internalID { get; set; }
        public Nullable<int> nt2_ordQty { get; set; }
        public Nullable<int> nt2_qtyForWMS { get; set; }
        public Nullable<int> nt2_fulfilledQty { get; set; }
        public Nullable<double> nt2_tax { get; set; }
        public Nullable<double> nt2_discount { get; set; }
        public Nullable<double> nt2_rate { get; set; }
        public Nullable<double> nt2_amount { get; set; }
        public string nt2_customer { get; set; }
        public string nt2_customer_internalID { get; set; }
        public string nt2_SEIS_moNo { get; set; }
        public string nt2_SEIS_moNo_internalID { get; set; }
        public string nt2_subsidiary { get; set; }
        public Nullable<System.DateTime> nt2_createdDate { get; set; }
        public Nullable<System.DateTime> nt2_rangeTo { get; set; }
        public string nt2_progressStatus { get; set; }
    }
}
