//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_jobordmaster_pack_history
    {
        public string nsjomp_jobOrdMaster_pack_ID { get; set; }
        public string nsjomp_jobOrdMaster_ID { get; set; }
        public string nsjomp_job_ID { get; set; }
        public string nsjomp_ordNo { get; set; }
        public string nsjomp_ordPack { get; set; }
        public string nsjomp_item_internalID { get; set; }
        public Nullable<int> nsjomp_qty { get; set; }
        public Nullable<int> nsjomp_ordQty { get; set; }
        public Nullable<double> nsjomp_ordPrice { get; set; }
        public string nsjomp_ordReplace { get; set; }
        public string nsjomp_ofrCode { get; set; }
        public string nsjomp_status { get; set; }
        public string nsjomp_ordPackStatus { get; set; }
        public Nullable<int> nsjomp_ordFulfill { get; set; }
        public Nullable<System.DateTime> nsjomp_ordDetDate { get; set; }
        public Nullable<double> nsjomp_ordPoint { get; set; }
        public string nsjomp_skuCode { get; set; }
        public string nsjomp_packTitle { get; set; }
        public string nsjomp_ofrDesc { get; set; }
        public string nsjomp_location_internalID { get; set; }
        public Nullable<double> nsjomp_tax { get; set; }
        public Nullable<double> nsjomp_discount { get; set; }
        public Nullable<int> nsjomp_orderLine { get; set; }
        public int nsjomp_recID { get; set; }
        public Nullable<System.DateTime> nsjomp_createdDate { get; set; }
        public Nullable<System.DateTime> nsjomp_rangeTo { get; set; }
        public string nsjomp_moNo { get; set; }
        public Nullable<double> nsjomp_ordRate { get; set; }
        public Nullable<double> nsjomp_basedprice { get; set; }
        public string nsjomp_pricelevel { get; set; }
        public string nsjomp_tax_code { get; set; }
        public Nullable<double> nsjomp_gstamount { get; set; }
    }
}
