//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_adjustment
    {
        public string nsda_adjustment_ID { get; set; }
        public string nsda_adjustment_code { get; set; }
        public Nullable<bool> nsda_adjustment_active { get; set; }
        public Nullable<bool> nsda_adjustment_posted { get; set; }
        public string nsda_adjustment_remarks { get; set; }
        public string nsda_adjustment_warehouse_ID { get; set; }
        public string nsda_adjustment_description { get; set; }
        public string nsda_adjustment_type { get; set; }
        public string nsda_createdBy { get; set; }
        public Nullable<System.DateTime> nsda_createdDate { get; set; }
        public string nsda_modifiedBy { get; set; }
        public Nullable<System.DateTime> nsda_modifiedDate { get; set; }
        public Nullable<System.DateTime> nsda_rangeTo { get; set; }
        public int nsda_recID { get; set; }
    }
}
