//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_jobmocls
    {
        public int nsjmc_recID { get; set; }
        public string nsjmc_jobMoCls_ID { get; set; }
        public string nsjmc_jobID { get; set; }
        public string nsjmc_jobMo_ID { get; set; }
        public string nsjmc_clsNo { get; set; }
        public string nsjmc_teacherName { get; set; }
        public Nullable<System.DateTime> nsjmc_createdDate { get; set; }
        public Nullable<System.DateTime> nsjmc_rangeTo { get; set; }
    }
}
