//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_pr
    {
        public string nspr_pr_ID { get; set; }
        public string nspr_businessChannel_ID { get; set; }
        public string nspr_businessChannel_internalID { get; set; }
        public string nspr_pr_accountClass { get; set; }
        public bool nspr_pr_active { get; set; }
        public string nspr_pr_approvalType { get; set; }
        public string nspr_pr_comments { get; set; }
        public System.DateTime nspr_pr_date { get; set; }
        public sbyte nspr_pr_day { get; set; }
        public string nspr_pr_deleteReason { get; set; }
        public string nspr_pr_deliveryMethod { get; set; }
        public string nspr_pr_desc { get; set; }
        public string nspr_pr_email { get; set; }
        public bool nspr_pr_exported { get; set; }
        public sbyte nspr_pr_month { get; set; }
        public Nullable<System.DateTime> nspr_pr_neededDate { get; set; }
        public string nspr_pr_number { get; set; }
        public string nspr_pr_requestor { get; set; }
        public string nspr_pr_site { get; set; }
        public short nspr_pr_status { get; set; }
        public string nspr_pr_supplier { get; set; }
        public string nspr_pr_supplier_internalID { get; set; }
        public short nspr_pr_year { get; set; }
        public string nspr_pr_internalID { get; set; }
        public string nspr_pr_location { get; set; }
        public string nspr_pr_location_internalID { get; set; }
        public string nspr_ns_status { get; set; }
        public Nullable<System.DateTime> nspr_createdDate { get; set; }
        public Nullable<System.DateTime> nspr_rangeTo { get; set; }
        public int nspr_recID { get; set; }
        public string nspr_pushStatus { get; set; }
    }
}
