//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_dropshipso
    {
        public int ds_recID { get; set; }
        public string ds_mono { get; set; }
        public string ds_mono_InternalID { get; set; }
        public Nullable<System.DateTime> ds_createdDate { get; set; }
        public Nullable<System.DateTime> ds_rangeTo { get; set; }
        public string ds_netsuiteGMYSOProgress { get; set; }
        public string ds_netsuiteClosedSOProgress { get; set; }
    }
}
