//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_jobmo_address
    {
        public string nsjma_jobMoAddress_ID { get; set; }
        public string nsjma_nsjm_jobMoID { get; set; }
        public string nsjma_jobMoAddress_name { get; set; }
        public string nsjma_jobMoAddress_1 { get; set; }
        public string nsjma_jobMoAddress_2 { get; set; }
        public string nsjma_jobMoAddress_3 { get; set; }
        public string nsjma_jobMoAddress_ref { get; set; }
        public string nsjma_moNo { get; set; }
        public string nsjma_jobMoAddress_contact { get; set; }
        public string nsjma_jobMoAddress_deliveryType { get; set; }
        public string nsjma_nsj_jobID { get; set; }
        public string nsjma_jobMoAddress_tag { get; set; }
        public string nsjma_jobMoAddress_tel { get; set; }
        public string nsjma_jobMoAddress_tel2 { get; set; }
        public string nsjma_jobMoAddress_fax { get; set; }
        public string nsjma_moNo_internalID { get; set; }
        public Nullable<System.DateTime> nsjma_createdDate { get; set; }
        public Nullable<System.DateTime> nsjma_rangeTo { get; set; }
        public int nsjma_recID { get; set; }
        public string nsjma_jobMoAddress_4 { get; set; }
    }
}
