//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_jobmo
    {
        public int nsjm_recID { get; set; }
        public string nsjm_nsj_job_ID { get; set; }
        public string nsjm_moNo { get; set; }
        public string nsjm_moNo_internalID { get; set; }
        public string nsjm_jobMo_ID { get; set; }
        public string nsjm_consignmentNote { get; set; }
        public Nullable<int> nsjm_clsCnt { get; set; }
        public string nsjm_contactPerson { get; set; }
        public string nsjm_country { get; set; }
        public string nsjm_deliveryAdd { get; set; }
        public string nsjm_deliveryAdd_2 { get; set; }
        public string nsjm_deliveryAdd_3 { get; set; }
        public Nullable<int> nsjm_ordRecNoCnt { get; set; }
        public string nsjm_postCode { get; set; }
        public string nsjm_processPeriod { get; set; }
        public string nsjm_schID { get; set; }
        public string nsjm_schName { get; set; }
        public string nsjm_status { get; set; }
        public string nsjm_telNo { get; set; }
        public Nullable<decimal> nsjm_ordWeight { get; set; }
        public string nsjm_schName_2 { get; set; }
        public string nsjm_jobNo { get; set; }
        public string nsjm_creditTerm { get; set; }
        public string nsjm_moCurrency { get; set; }
        public string nsjm_deliveryType { get; set; }
        public string nsjm_moLisence { get; set; }
        public string nsjm_moTransMode { get; set; }
        public Nullable<System.DateTime> nsjm_tranDate { get; set; }
        public string nsjm_ns_status { get; set; }
        public Nullable<System.DateTime> nsjm_createdDate { get; set; }
        public Nullable<System.DateTime> nsjm_rangeTo { get; set; }
        public Nullable<System.DateTime> nsjm_shipDate { get; set; }
        public string is_fas { get; set; }
    }
}
