//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuite_jobordmaster_packdetail_history
    {
        public string nsjompd_jobOrdMaster_packDetail_ID { get; set; }
        public string nsjompd_jobOrdMaster_pack_ID { get; set; }
        public string nsjompd_job_ID { get; set; }
        public string nsjompd_ordPack { get; set; }
        public string nsjompd_skuNo { get; set; }
        public string nsjompd_isbn { get; set; }
        public string nsjompd_isbn_secondary { get; set; }
        public string nsjompd_item_internalID { get; set; }
        public Nullable<short> nsjompd_sku_qty { get; set; }
        public string nsjompd_item_ID { get; set; }
        public Nullable<short> nsjompd_total_qty { get; set; }
        public Nullable<short> nsjompd_scanned_qty { get; set; }
        public int nsjompd_recID { get; set; }
        public Nullable<System.DateTime> nsjompd_createdDate { get; set; }
        public Nullable<System.DateTime> nsjompd_rangeTo { get; set; }
        public string nsjompd_tax_code { get; set; }
        public Nullable<double> nsjompd_item_price { get; set; }
        public Nullable<double> nsjompd_gstamount { get; set; }
        public Nullable<double> nsjompd_deliveryCharge { get; set; }
        public Nullable<double> nsjompd_deliveryChargeGst { get; set; }
    }
}
