//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsuitedataformq
    {
        public int id { get; set; }
        public string mq_transactionType { get; set; }
        public string mq_nsj_jobID { get; set; }
        public string mq_internalID { get; set; }
        public string mq_consolidateTable { get; set; }
        public string mq_status { get; set; }
        public Nullable<System.DateTime> mq_pushDate { get; set; }
        public Nullable<System.DateTime> mq_pullDate { get; set; }
        public Nullable<System.DateTime> mq_updatedDate { get; set; }
        public string mq_tranID { get; set; }
    }
}
