//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patchdata
    {
        public string jobordmaster_pack_id { get; set; }
        public string moNo { get; set; }
        public string moNo_InternalID { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<double> basedprice { get; set; }
        public string pricelevel { get; set; }
        public string item_isbn { get; set; }
        public int recid { get; set; }
        public string isRun { get; set; }
        public string status { get; set; }
    }
}
