//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestnetsuite
    {
        public string rn_sche_transactionType { get; set; }
        public Nullable<System.DateTime> rn_createdDate { get; set; }
        public string rn_status { get; set; }
        public Nullable<long> rn_seqNo { get; set; }
        public string rn_jobID { get; set; }
        public string rn_parentJobID { get; set; }
        public Nullable<System.DateTime> rn_rangeFrom { get; set; }
        public Nullable<System.DateTime> rn_rangeTo { get; set; }
        public Nullable<System.DateTime> rn_completedAt { get; set; }
        public Nullable<System.DateTime> rn_updatedDate { get; set; }
        public Nullable<int> rn_sequence { get; set; }
        public int rn_id { get; set; }
    }
}
