//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestmq
    {
        public string rmq_sche_transactionType { get; set; }
        public Nullable<System.DateTime> rmq_createdDate { get; set; }
        public string rmq_status { get; set; }
        public Nullable<long> rmq_seqNo { get; set; }
        public string rmq_jobID { get; set; }
        public Nullable<System.DateTime> rmq_rangeFrom { get; set; }
        public Nullable<System.DateTime> rmq_rangeTo { get; set; }
        public Nullable<System.DateTime> rmq_completedAt { get; set; }
        public Nullable<System.DateTime> rmq_updatedDate { get; set; }
        public Nullable<int> rmq_sequence { get; set; }
        public int rmq_id { get; set; }
    }
}
