//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduler
    {
        public string sche_transactionType { get; set; }
        public string sche_status { get; set; }
        public string sche_minuteGap { get; set; }
        public Nullable<System.DateTime> sche_nextRun { get; set; }
        public Nullable<int> sche_nextRunSeqNo { get; set; }
        public Nullable<System.DateTime> sche_lastRun { get; set; }
        public Nullable<int> sche_lastRunSeqNo { get; set; }
        public Nullable<System.DateTime> sche_date { get; set; }
        public Nullable<int> sche_sequence { get; set; }
        public int sche_id { get; set; }
        public string sche_desc { get; set; }

        //ANET-23 - Scheduler Control Handling
        //Added by Brash Developer on 16-Jul-2021
        public int sche_wait { get; set; }
    }
}
