//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int School_ID { get; set; }
        public string School_Name { get; set; }
        public string School_Standard { get; set; }
        public string School_Address { get; set; }
        public string School_Country { get; set; }
        public string School_Email { get; set; }
        public string School_Section { get; set; }
    }
}
