//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_resync
    {
        public int recid { get; set; }
        public string mono { get; set; }
        public string mono_internalID { get; set; }
        public string itemISBN { get; set; }
        public Nullable<int> ordqty { get; set; }
        public Nullable<int> qtyforwms { get; set; }
        public Nullable<int> wmsfulfilledqty { get; set; }
        public Nullable<int> updateqty { get; set; }
    }
}
