//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_unfulfillso
    {
        public int rec_id { get; set; }
        public string uf_mono { get; set; }
        public string uf_itemInternalID { get; set; }
        public Nullable<int> uf_fulfillQty { get; set; }
    }
}
