//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tosyncitem
    {
        public string item_isbn { get; set; }
        public string item_internalID { get; set; }
        public int recID { get; set; }
        public string isDone { get; set; }
    }
}
