//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unfulfillso
    {
        public int uf_recID { get; set; }
        public string uf_transactiontype { get; set; }
        public string uf_mono { get; set; }
        public string uf_itemInternalID { get; set; }
        public Nullable<int> uf_fulfillQty { get; set; }
        public Nullable<System.DateTime> uf_rangeFrom { get; set; }
        public Nullable<System.DateTime> uf_rangeTo { get; set; }
        public Nullable<System.DateTime> uf_createdDate { get; set; }
        public string uf_remarks { get; set; }
    }
}
