//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unscan
    {
        public int ef_recID { get; set; }
        public string ef_moNo { get; set; }
        public string ef_nsjom_jobOrdMasterID { get; set; }
        public string ef_josp_packID { get; set; }
        public string ef_item_InternalID { get; set; }
        public Nullable<int> ef_excessQty { get; set; }
        public string ef_refNo { get; set; }
        public Nullable<System.DateTime> ef_createdDate { get; set; }
        public Nullable<System.DateTime> ef_rangeTo { get; set; }
    }
}
