//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int u_id { get; set; }
        public string u_firstName { get; set; }
        public string u_lastName { get; set; }
        public string u_email { get; set; }
        public string u_userName { get; set; }
        public string u_password { get; set; }
        public string u_createdBy { get; set; }
        public Nullable<System.DateTime> u_createdDate { get; set; }
        public Nullable<System.DateTime> u_modifiedDate { get; set; }
        public string u_role { get; set; }
    }
}
