//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_wms_jobordscan
    {
        public string jos_country_tag { get; set; }
        public string jos_job_ID { get; set; }
        public string jos_jobmo_ID { get; set; }
        public Nullable<System.DateTime> jos_scanDate { get; set; }
        public string jos_moNo { get; set; }
        public string jos_businessChannel_ID { get; set; }
        public string jos_businessChannel_code { get; set; }
        public Nullable<System.DateTime> jos_exportDate { get; set; }
        public Nullable<System.DateTime> jos_rangeTo { get; set; }
        public long numOfRec { get; set; }
    }
}
