//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_directadjustment
    {
        public string da_directAdjID { get; set; }
        public string da_account_internalID { get; set; }
        public string da_subsidiary_internalID { get; set; }
        public string da_businessChannel_internalID { get; set; }
        public Nullable<System.DateTime> da_tranDate { get; set; }
        public Nullable<System.DateTime> da_createdDate { get; set; }
        public Nullable<System.DateTime> da_rangeTo { get; set; }
        public int da_recID { get; set; }
    }
}
