//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_jobordscan
    {
        public string jos_jobordscan_ID { get; set; }
        public string jos_consignmentNote { get; set; }
        public string jos_country_tag { get; set; }
        public string jos_deliveryRef { get; set; }
        public string jos_job_ID { get; set; }
        public string jos_jobmo_ID { get; set; }
        public string jos_ordRecNo { get; set; }
        public Nullable<System.DateTime> jos_scanDate { get; set; }
        public string jos_moNo { get; set; }
        public string jos_businessChannel_ID { get; set; }
        public string jos_businessChannel_code { get; set; }
        public Nullable<System.DateTime> jos_exportDate { get; set; }
        public string jos_load_ind { get; set; }
        public string jos_doNo { get; set; }
        public string jos_jobOrdMaster_ID { get; set; }
        public Nullable<System.DateTime> jos_createdDate { get; set; }
        public Nullable<System.DateTime> jos_rangeTo { get; set; }
        public int jos_recID { get; set; }
        public string jos_netsuiteProgress { get; set; }
        public string jos_netsuiteProgressDummy { get; set; }
        public string jos_syncupdate { get; set; }
        public string jos_GMYInvoiceProgress { get; set; }
        public string jos_dropshipFulfillmentProgress { get; set; }
    }
}
