//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_directtransferitem
    {
        public string dti_dt_directTransfer_ID { get; set; }
        public string dti_productCode { get; set; }
        public Nullable<decimal> dti_quantity { get; set; }
        public int dti_recID { get; set; }
    }
}
