//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_rareceiveitem
    {
        public string nsri_rritem_ID { get; set; }
        public string nsri_nsr_rr_ID { get; set; }
        public string nsri_rritem_invoice { get; set; }
        public string nsri_rritem_isbn { get; set; }
        public string nsri_rritem_isbn2 { get; set; }
        public Nullable<int> nsri_rritem_return_qty { get; set; }
        public Nullable<System.DateTime> nsri_tranDate { get; set; }
        public string nsri_createdBy { get; set; }
        public Nullable<int> nsri_rritem_status { get; set; }
        public string nsri_remarks { get; set; }
        public Nullable<int> nsri_rritem_max_return { get; set; }
        public string nsri_item_internalID { get; set; }
        public Nullable<int> nsri_rritem_receive_qty { get; set; }
        public string nsri_cn_id { get; set; }
        public Nullable<int> nsri_rritem_posting_qty { get; set; }
        public string nsri_pack_ID { get; set; }
        public Nullable<System.DateTime> nsri_createdDate { get; set; }
        public int nsri_recID { get; set; }
        public string nsri_netsuiteRA { get; set; }
    }
}
