//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_directadjustmentitem
    {
        public int dai_recID { get; set; }
        public string dai_da_directAdjID { get; set; }
        public string dai_itemID { get; set; }
        public string dai_item_internalID { get; set; }
        public string dai_qty { get; set; }
        public string dai_location_internalID { get; set; }
    }
}
