//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_rareceive
    {
        public string nsr_rr_ID { get; set; }
        public string nsr_rr_schID { get; set; }
        public string nsr_rr_number { get; set; }
        public string nsr_rr_internalID { get; set; }
        public Nullable<System.DateTime> nsr_rr_date { get; set; }
        public string nsr_rr_description { get; set; }
        public string nsr_rr_createdBy { get; set; }
        public string nsr_rr_reference { get; set; }
        public Nullable<bool> nsr_rr_active { get; set; }
        public Nullable<System.DateTime> nsr_rr_returnDate { get; set; }
        public string nsr_rr_returnBy { get; set; }
        public Nullable<int> nsr_rr_status { get; set; }
        public string nsr_period { get; set; }
        public string nsr_ns_status { get; set; }
        public Nullable<System.DateTime> nsr_createdDate { get; set; }
        public Nullable<System.DateTime> nsr_rangeTo { get; set; }
        public int nsr_recID { get; set; }
        public string nsr_netsuiteRA { get; set; }
    }
}
