//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_jobordscan_pack
    {
        public string josp_pack_ID { get; set; }
        public string josp_status { get; set; }
        public Nullable<int> josp_ordFulFill { get; set; }
        public Nullable<double> josp_ordPoint { get; set; }
        public string josp_posted_ind { get; set; }
        public string josp_jobOrdMaster_ID { get; set; }
        public Nullable<System.DateTime> josp_createdDate { get; set; }
        public Nullable<System.DateTime> josp_rangeTo { get; set; }
        public int josp_recID { get; set; }
        public Nullable<int> josp_excessQty { get; set; }
        public string josp_moNo { get; set; }
        public string josp_jobID { get; set; }
        public string josp_ordRecNo { get; set; }
        public Nullable<System.DateTime> josp_exportDate { get; set; }
        public Nullable<int> josp_ordUnFulFill { get; set; }
    }
}
