//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_excessporeceive
    {
        public int epor_recID { get; set; }
        public string epor_prID { get; set; }
        public string epor_poreceive_ID { get; set; }
        public string epor_item_ID { get; set; }
        public string epor_item_internalID { get; set; }
        public Nullable<int> epor_qty { get; set; }
        public Nullable<System.DateTime> epor_createdDate { get; set; }
    }
}
