//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_directtransfer
    {
        public string dt_directTransfer_ID { get; set; }
        public string dt_reference { get; set; }
        public Nullable<System.DateTime> dt_sessionDate { get; set; }
        public string dt_userID { get; set; }
        public string dt_locationFrom { get; set; }
        public string dt_locationTo { get; set; }
        public string dt_businessChannel { get; set; }
        public Nullable<System.DateTime> dt_createdDate { get; set; }
        public Nullable<System.DateTime> dt_rangeTo { get; set; }
        public int dt_recID { get; set; }
    }
}
