//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_poreceive
    {
        public string po_poreceive_ID { get; set; }
        public string po_createdBy { get; set; }
        public string po_modifiedBy { get; set; }
        public Nullable<System.DateTime> po_modifiedDate { get; set; }
        public Nullable<bool> po_poreceive_active { get; set; }
        public string po_poreceive_desc { get; set; }
        public string po_poreceive_number { get; set; }
        public string po_poreceive_invoice { get; set; }
        public string po_poreference_ID { get; set; }
        public string po_pr_ID { get; set; }
        public Nullable<System.DateTime> po_createdDate { get; set; }
        public Nullable<System.DateTime> po_rangeTo { get; set; }
        public int po_recID { get; set; }
        public string po_netsuitePO { get; set; }
    }
}
