//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sde.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_cashsaleitem
    {
        public int csi_recID { get; set; }
        public string csi_cs_cashsaleID { get; set; }
        public string csi_itemID { get; set; }
        public string csi_item_internalID { get; set; }
        public string csi_qty { get; set; }
    }
}
